# Generated by Django 6.0.2 on 2026-02-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_conversation_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='customer_email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='customer_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='customer_phone',
            new_name='client_phone',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='issue_title',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='order_ref',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='store_domain',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='store_name',
        ),
        migrations.AddField(
            model_name='conversation',
            name='affected_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='enterprise',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='conversation',
            name='problem_subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='conversation',
            name='satisfaction_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='conversation',
            name='satisfaction_stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
