# Generated by Django 6.0.2 on 2026-02-18 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_rename_customer_email_conversation_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='resolution_method',
            field=models.CharField(choices=[('ai_resolved', 'ai_resolved'), ('escalated', 'escalated'), ('abandoned', 'abandoned'), ('unknown', 'unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('error_pattern', models.CharField(db_index=True, max_length=200)),
                ('severity', models.CharField(db_index=True, default='high', max_length=10)),
                ('status', models.CharField(choices=[('open', 'open'), ('acknowledged', 'acknowledged'), ('resolved', 'resolved')], db_index=True, default='open', max_length=20)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('conversation_ids', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'status', 'last_seen'], name='support_inc_tenant__e0fd72_idx')],
            },
        ),
    ]
